package com.shreeai.os.platform.kernels.knowledge.model;

import java.time.Instant;
import java.util.Map;
import java.util.Objects;

/**
 * <b>KnowledgeSource</b>
 *
 * <p>The canonical, immutable description of a single registered knowledge
 * source in Shree AI OS. A knowledge source is a <em>reference</em> to an
 * origin of knowledge - it contains no content, only metadata.</p>
 *
 * <p><b>Immutability:</b> This record is deeply immutable. The {@code metadata}
 * map is defensively copied on construction and never exposed mutably.</p>
 *
 * <p><b>Deterministic Identity:</b> The {@code sourceId} is generated by the
 * {@code KnowledgeSourceRegistry} from {@code type + normalizedLocation + name}
 * and is therefore identical for identical registration input - it is never a
 * random value.</p>
 *
 * <p><b>Ownership:</b> Knowledge Kernel - K1 Universal Knowledge Source Registry</p>
 * <p><b>Version:</b> 1.0</p>
 *
 * @param sourceId the deterministic registry identifier (must not be null)
 * @param name the human-readable source name (must not be null)
 * @param type the source family (must not be null)
 * @param status the current lifecycle state (must not be null)
 * @param location the physical or logical location (must not be null)
 * @param description an optional human-readable description
 * @param registeredAt when the source was registered (must not be null)
 * @param metadata arbitrary source metadata (never null, defensively copied)
 */
public record KnowledgeSource(
        String sourceId,
        String name,
        KnowledgeSourceType type,
        KnowledgeSourceStatus status,
        String location,
        String description,
        Instant registeredAt,
        Map<String, String> metadata) {

    /**
     * Compact constructor that validates required fields and defensively copies
     * the metadata map so the record is deeply immutable.
     *
     * @throws NullPointerException if any required field is null
     */
    public KnowledgeSource {
        Objects.requireNonNull(sourceId, "sourceId must not be null");
        Objects.requireNonNull(name, "name must not be null");
        Objects.requireNonNull(type, "type must not be null");
        Objects.requireNonNull(status, "status must not be null");
        Objects.requireNonNull(location, "location must not be null");
        Objects.requireNonNull(registeredAt, "registeredAt must not be null");
        metadata = metadata == null ? Map.of() : Map.copyOf(metadata);
    }

    /**
     * Creates a fully-immutable KnowledgeSource with all identity fields.
     *
     * @param sourceId the deterministic registry identifier
     * @param name the human-readable source name
     * @param type the source family
     * @param status the current lifecycle state
     * @param location the physical or logical location
     * @param description an optional human-readable description
     * @param registeredAt when the source was registered
     * @param metadata arbitrary source metadata (copied defensively)
     * @return a new immutable KnowledgeSource (never null)
     */
    public static KnowledgeSource of(String sourceId,
                                     String name,
                                     KnowledgeSourceType type,
                                     KnowledgeSourceStatus status,
                                     String location,
                                     String description,
                                     Instant registeredAt,
                                     Map<String, String> metadata) {
        return new KnowledgeSource(sourceId, name, type, status, location,
                description, registeredAt, metadata);
    }

    /**
     * Returns a new KnowledgeSource with the given lifecycle status, preserving
     * every other field (including the deterministic sourceId).
     *
     * @param status the new lifecycle state (must not be null)
     * @return a new immutable KnowledgeSource (never null)
     */
    public KnowledgeSource withStatus(KnowledgeSourceStatus status) {
        Objects.requireNonNull(status, "status must not be null");
        return new KnowledgeSource(sourceId, name, type, status, location,
                description, registeredAt, metadata);
    }
}