package com.shreeai.os.platform.learning.adaptive;

import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Immutable recommendation object produced by RecommendationEngine.
 *
 * Contains deterministic guidance for the student's next learning steps.
 * Never generated by an LLM — always computed from structured data.
 */
public final class Recommendation {

    public enum Action {
        /** Proceed to the next lesson in sequence */
        CONTINUE,
        /** Review and repeat the current lesson */
        REPEAT,
        /** Skip to a more advanced topic */
        SKIP_AHEAD,
        /** Focus on weak topics for revision */
        REVISE_WEAK,
        /** The course is complete */
        COURSE_COMPLETE
    }

    private final Action recommendedAction;
    private final String recommendedTopic;
    private final DifficultyLevel suggestedDifficulty;
    private final List<String> topicsToRevise;
    private final String rationale;

    public Recommendation(Action recommendedAction,
                          String recommendedTopic,
                          DifficultyLevel suggestedDifficulty,
                          List<String> topicsToRevise,
                          String rationale) {
        this.recommendedAction = recommendedAction;
        this.recommendedTopic = recommendedTopic != null ? recommendedTopic : "";
        this.suggestedDifficulty = suggestedDifficulty != null ? suggestedDifficulty : DifficultyLevel.NORMAL;
        this.topicsToRevise = topicsToRevise != null
                ? Collections.unmodifiableList(List.copyOf(topicsToRevise))
                : List.of();
        this.rationale = rationale != null ? rationale : "";
    }

    public Action getRecommendedAction() { return recommendedAction; }
    public String getRecommendedTopic() { return recommendedTopic; }
    public DifficultyLevel getSuggestedDifficulty() { return suggestedDifficulty; }
    public List<String> getTopicsToRevise() { return topicsToRevise; }
    public String getRationale() { return rationale; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Recommendation that)) return false;
        return recommendedAction == that.recommendedAction
                && recommendedTopic.equals(that.recommendedTopic)
                && suggestedDifficulty == that.suggestedDifficulty
                && topicsToRevise.equals(that.topicsToRevise)
                && rationale.equals(that.rationale);
    }

    @Override
    public int hashCode() {
        return Objects.hash(recommendedAction, recommendedTopic,
                suggestedDifficulty, topicsToRevise, rationale);
    }

    @Override
    public String toString() {
        return "Recommendation{" +
                "action=" + recommendedAction +
                ", topic='" + recommendedTopic + '\'' +
                ", difficulty=" + suggestedDifficulty +
                ", revise=" + topicsToRevise +
                ", rationale='" + rationale + '\'' +
                '}';
    }
}