package com.shreeai.os.platform.kernels.inference.model;

import java.util.List;
import java.util.Objects;

/**
 * <b>AlternativeCandidate</b>
 *
 * <p>One immutable, executable solution alternative generated by the I1
 * engine: a strategy category, a human-readable title, the ordered steps of
 * the path and the deterministic feasibility of the path.</p>
 *
 * <p><b>Deterministic identity:</b> {@code candidateId} is derived by the
 * generation engine as {@code SHA-256(type | title | step titles)} and is
 * stable across identical inputs - there is no UUID and no randomness.</p>
 *
 * <p><b>Feasibility is not confidence.</b> Feasibility is the locked
 * deterministic ratio:</p>
 * <pre>feasibility = completedPrerequisites / totalSteps</pre>
 * <p>It answers exactly one question - <em>can this path realistically
 * satisfy the goal?</em> - and is clamped to {@code [0.0, 1.0]}. It is never
 * a probability, never a prediction and never a quality score; comparison of
 * candidates belongs to I2 Trade-off Analysis.</p>
 *
 * <p><b>Immutability:</b> This record is deeply immutable - the step list is
 * defensively copied and unmodifiable, and every step is immutable.</p>
 * <p><b>Thread Safety:</b> Records are inherently thread-safe.</p>
 *
 * <p><b>Ownership:</b> Inference Kernel - I1 Alternative Generation</p>
 * <p><b>Version:</b> 1.0</p>
 *
 * @param candidateId the deterministic SHA-256 candidate id (never null or
 *                    blank)
 * @param type        the strategy category (never null)
 * @param title       the human-readable candidate title (never null or blank)
 * @param steps       the ordered immutable step list (never null)
 * @param feasibility the deterministic feasibility within {@code [0.0, 1.0]}
 */
public record AlternativeCandidate(
        String candidateId,
        AlternativeType type,
        String title,
        List<AlternativeStep> steps,
        double feasibility) {

    /**
     * Creates a deeply-immutable AlternativeCandidate with validation.
     *
     * @throws NullPointerException     if any reference field is null
     * @throws IllegalArgumentException if candidateId or title is blank, the
     *                                  step list is empty, or feasibility is
     *                                  outside {@code [0.0, 1.0]}
     */
    public AlternativeCandidate {
        Objects.requireNonNull(candidateId, "candidateId must not be null");
        Objects.requireNonNull(type, "type must not be null");
        Objects.requireNonNull(title, "title must not be null");
        Objects.requireNonNull(steps, "steps must not be null");
        if (candidateId.isBlank()) {
            throw new IllegalArgumentException("candidateId must not be blank");
        }
        if (title.isBlank()) {
            throw new IllegalArgumentException("title must not be blank");
        }
        if (steps.isEmpty()) {
            throw new IllegalArgumentException("steps must not be empty");
        }
        if (feasibility < 0.0 || feasibility > 1.0) {
            throw new IllegalArgumentException(
                    "feasibility must be within [0.0, 1.0]: " + feasibility);
        }
        steps = List.copyOf(steps);
    }

    /**
     * Returns the number of steps in this candidate.
     *
     * @return the step count (never negative)
     */
    public int stepCount() {
        return steps.size();
    }

    @Override
    public String toString() {
        return String.format("AlternativeCandidate{type=%s, title=%s, steps=%d, feasibility=%.4f}",
                type, title, steps.size(), feasibility);
    }
}
